name: pylint score

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    stylechecking:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9.2
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9.2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint beautifulsoup4 blingfire flask flask-cors markdown markdown-checklist mdx-gh-links mypy numpy pygithub sqlalchemy torch transformers[torch]
            - name: Run linting
              run: |
                  bash scripts/linux/style_checking.sh > linting.txt
            - name: Archive linting report
              uses: actions/upload-artifact@v2
              with:
                  name: linting-report
                  path: |
                      linting.txt
